blog_project/blog/urls.py
from django.urls import path
from blog.views import delete_reply,reply,PostListView,postDetailView,PostCreateView,PostUpdateView,postDeleteView,UserPostListView
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('about/', views.about, name='blog-about'),
    path('post/<int:pk>/', postDetailView, name='post-detail'),
    path('post/<int:pk>/delete/', postDeleteView, name='post-delete'),
    path('post/new/', PostCreateView.as_view(), name='post-new'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/reply/<int:pk>/<int:v>/', reply, name='reply'),
    path('post/reply/delete/<int:pk>/<int:v>/', delete_reply, name='delete-reply'),

]

blog_project/blog_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views
from artificial_intelligence import views as learn_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('register/',user_views.register,name='register'),
    path('activate/<uidb64>/<token>/',user_views.activate,name='activate'),
    path('profile/',user_views.profile,name='profile'),

    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    path('password-reset-done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),

    path('',include('blog.urls')),
    path('store/',include('store.urls')),

    path('learning/',learn_views.learning_view,name='learning'),
    path('learning/save_object/<int:age>/',learn_views.save_object,name='save_object'),

]
# to add media routes to url patterns
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog_project/store/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('cart/',views.cart,name='cart'),
    path('cart/add_order/<int:pk>/',views.createOrder,name='create_order'),
    path('store/',views.ProductListView.as_view(),name='store'),
    path('store/new_item',views.ProductCreateView.as_view(),name='store_new_item'),
    path('store/item/<int:pk>/',views.ProductDetailView.as_view(),name='store_item'),
    path('store/update_item/<int:pk>/',views.ProductUpdateView.as_view(),name='store_item_update'),
    path('checkOut/',views.checkOut,name='checkOut'),
    path('cart/update_quantity/',views.updateQuantity,name='update_quantity'),
]

blog_project/store/models.py
from django.db import models
from django.urls import reverse
from PIL import Image

from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    image = models.ImageField(default='Anime_12.jpg',upload_to='products')
    title = models.CharField(max_length=100)
    about = models.CharField(max_length=100)
    discription = models.TextField()
    price = models.IntegerField()
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('store_item', kwargs={'pk':self.id})

class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(User,on_delete=models.CASCADE,related_query_name='orders')
    quantity = models.IntegerField(default=1)

    @property
    def total(self):
        total = 0
        for order in User.objects.all().filter(id=self.customer.id).first().order_set.all():
            total += order.product.price * order.quantity
        return total

    

blog_project/store/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView,DetailView,CreateView,UpdateView
from store.models import Product,Order
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import json
# Create your views here.

class ProductListView(ListView):
    model = Product
    template_name = 'store/store.html'
    ordering = ['-date']

class ProductDetailView(DetailView):
    model = Product

class ProductCreateView(UserPassesTestMixin, CreateView):
    model = Product
    fields = ['image','title','price','about','discription']

    def test_func(self):
        return self.request.user.is_superuser

class ProductUpdateView(UserPassesTestMixin, UpdateView):
    model = Product
    fields = ['image','title','price','about','discription']

    def test_func(self):
        return self.request.user.is_superuser

# function for Cart
@login_required
def cart(request):
    return render(request,'store/cart.html')

@login_required
def createOrder(request,pk):
    product = Product.objects.get(pk=pk)
    order, created = Order.objects.get_or_create(product=product, customer=request.user)
    return redirect('store')

@login_required
def updateQuantity(request):
    data = json.loads(request.body)
    orderId = data['orderId']
    action = data['action']

    order = Order.objects.get(id=orderId)

    if action=='add':
       order.quantity = order.quantity + 1
    elif action=='remove':
       order.quantity = order.quantity - 1

    order.save()

    if order.quantity <= 0:
       order.delete()

    return JsonResponse('fetching is complete', safe=False)

@login_required
def checkOut(request):
    return render(request,'store/checkOut.html')

blog_project/store/templates/store/cart.html
{% extends "blog/base.html" %}
{% block content %}

  <div class="row">
    <div class="col-lg-12" style="min-width:1001px;">
      <div class="box-element">
      	<a  class="btn btn-outline-dark" href="{% url 'store' %}">&#x2190; Continue Shopping</a>
      	<br>
      	<br>
      	<table class="table">
      		<tr>
      			<th><h5>Items: <strong>{{user.order_set.count}}</strong></h5></th>
      			<th><h5>Total:<strong> ${{user.order_set.all.first.total}}</strong></h5></th>
      			<th>
      				<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'checkOut' %}">Checkout</a>
      			</th>
      		</tr>
      	</table>
      </div>

      <br>
      <div class="box-element">
      	<div class="cart-row">
      		<div style="flex:2"></div>
      		<div style="flex:2"><strong>Item</strong></div>
      		<div style="flex:1"><strong>Price</strong></div>
      		<div style="flex:1"><strong>Quantity</strong></div>
      		<div style="flex:1"><strong>Total</strong></div>
      	</div>
        {% for order in user.order_set.all %}
      	<div class="cart-row">
      		<div style="flex:2; height:100px;"><img style="width:100px; height:100%" src="{{order.product.image.url}}"></div>
          <div style="flex:2"><strong>{{order.product.title}}</strong>

          </div>
      		<div style="flex:1"><p>${{order.product.price}}</p></div>
      		<div style="flex:1; min-width:170px" class="col">
      			<p class="quantity row">{{order.quantity}}</p>
      			<div class="quantity row ml-4" style="max-width:120px">
              <img style="width:10%; height:10%" class="update-cart chg-quantity" data-action="add" data-order="{{order.id}}" src="https://dejpknyizje2n.cloudfront.net/svgcustom/clipart/preview/triangle-shape-2594-13858-550x550.png">
              <br/>
              <img style="width:10%; height:10%" class="update-cart chg-quantity" data-action="remove" data-order="{{order.id}}" src="https://www.shareicon.net/data/2015/11/09/669555_triangle_512x512.png">
      			</div>
      		</div>
      		<div style="flex:1"><p>${%widthratio order.product.price 1 order.quantity%}</p></div>
      	</div>
        {% endfor %}
    </div>
  </div>

{% endblock %}

blog_project/store/templates/store/checkOut.html
{% extends "blog/base.html" %}
{% block content %}
     <div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form" action="#">
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>

					<div id="shipping-info">
						<hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Zip code..">
						</div>
					</div>

					<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
				</form>
			</div>
		</div>

		<div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
				{% for order in user.order_set.all %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{order.product.image.url}}"></div>
					<div style="flex:2"><p>{{order.product.title}}</p></div>
					<div style="flex:1"><p>${{order.product.price|floatformat:2}}</p></div>
					<div style="flex:1"><p>x{{order.quantity}}</p></div>
				</div>
				{% endfor %}
				<h5>Items:   {{user.order_set.count}}</h5>
				<h5>Total:   ${{user.order_set.all.first.total}}</h5>
			</div>
		</div>
	</div>
{% endblock content %}

blog_project/store/templates/store/product_detail.html
{% extends "blog/base.html" %}
{% block content %}
  <article class="media content-section">
    <img style='width:250px; height:250px;' class="article-img" src="{{ object.image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <small class="text-muted">{{ object.date|date:"F d, Y" }}</small>
      </div>
      <h1 class="article-title">{{ object.title }}</h1>
      <h4>${{ object.price }}</h4>
      <p class="article-content">{{ object.about }}</p>
      <p class="article-content">{{ object.discription }}</p>
    </div>
  </article>
  {% if user.is_superuser %}
    <a class="btn btn-success mt-1 mb-1" href="{% url 'store_item_update' pk=object.id %}">Update</a>
  {% endif %}
{% endblock content %}

blog_project/store/templates/store/product_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Item</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Add Item</button>
            </div>
        </form>
    </div>
{% endblock content %}

blog_project/store/templates/store/store.html
{% extends "blog/base.html" %}
{% block content %}
<div class="row inline-flex">
  {% for product in product_list %}
  <div class="col mb-4" style="min-width:250px; max-width:400px; display: inline-block;">
    <img style="weight:100%" class="thumbnail" src="{{ product.image.url }}" onclick="location.href='{% url 'store_item' pk=product.id %}';">
    <div class="box-element product">
      <h6><strong>{{product.title}}</strong></h6>
      <hr>

      <a  class="btn btn-outline-success add-btn" href="{% url 'create_order' pk=product.id %}">Add to Cart</a>
      <h4 style="display: inline-block; float: right"><strong>${{product.price}}</strong></h4>

    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}