blog_project/blog/urls.py
from django.urls import path
from blog.views import delete_reply,reply,PostListView,postDetailView,PostCreateView,PostUpdateView,postDeleteView,UserPostListView
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('about/', views.about, name='blog-about'),
    path('post/<int:pk>/', postDetailView, name='post-detail'),
    path('post/<int:pk>/delete/', postDeleteView, name='post-delete'),
    path('post/new/', PostCreateView.as_view(), name='post-new'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/reply/<int:pk>/<int:v>/', reply, name='reply'),
    path('post/reply/delete/<int:pk>/<int:v>/', delete_reply, name='delete-reply'),

]

blog_project/blog_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views
from artificial_intelligence import views as learn_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('register/',user_views.register,name='register'),
    path('activate/<uidb64>/<token>/',user_views.activate,name='activate'),
    path('profile/',user_views.profile,name='profile'),

    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    path('password-reset-done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),

    path('',include('blog.urls')),
    path('store/',include('store.urls')),

    path('learning/',learn_views.learning_view,name='learning'),
    path('learning/save_object/<int:age>/',learn_views.save_object,name='save_object'),

]
# to add media routes to url patterns
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog_project/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    # if we want to update the date then we can use auto_now=True and if we want to fix the date then we can use default=timezone.now
    date_posted = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk':self.id})

class Reply(models.Model):
    to_reply = models.IntegerField(blank=True, null=True)
    message = models.CharField(max_length=400)
    left_margin = models.IntegerField(default=0)
    color_style = models.CharField(max_length=300, default="w3-flat-nephritis")
    postId = models.IntegerField(blank=True, null=True)

blog_project/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Reply
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 6

class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_post.html'
    context_object_name = 'posts'

    def get_queryset(self):
        user=get_object_or_404(User, username = self.kwargs.get('username'))
        return Post.objects.filter(author = user).order_by('-date_posted')

# class PostDetailView(DetailView):
#     model = Post

def make_reply(toreply):
    jist = []
    new_reply = Reply.objects.all().filter(to_reply=toreply)

    for new in new_reply:
        jist = jist + [new]
        jist = jist + make_reply(new.id)

    return jist

def postDetailView(request, pk):
    object = Post.objects.get(pk=pk)
    toreply,created = Reply.objects.get_or_create(message="Type your reply..", postId=object.id)
    reply_list = []
    reply_list += [toreply]
    reply_list += make_reply(toreply.id)

    return render(request, 'blog/post_detail.html', {'object':object, 'reply_list':reply_list})

class PostCreateView(LoginRequiredMixin,CreateView):
    model = Post
    fields = ['title','text']

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = Post
    fields = ['title','text']

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if post.author == self.request.user:
            return True
        return False

@login_required
def postDeleteView(request, pk):
    post = Post.objects.get(pk=pk)
    if post.author == request.user:
        reply = Reply.objects.get(postId=post.id)
        delete_func(reply.pk)
        reply.delete()
        post.delete()
    return redirect('blog-home')

def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})

def reply(request, pk, v):
    if request.method == 'POST':
        form_data = request.POST['message']

        left_margin = Reply.objects.get(pk=pk).left_margin + 20

        if pk % 10 == 0:
            color_field = "w3-metro-green"
        elif pk % 10 == 1:
            color_field = "w3-metro-blue"
        elif pk % 10 == 2:
            color_field = "w3-metro-magenta"
        elif pk % 10 == 3:
            color_field = "w3-flat-sun-flower"
        elif pk % 10 == 4:
            color_field = "w3-flat-emerald"
        elif pk % 10 == 5:
            color_field = "w3-flat-belize-hole"
        elif pk % 10 == 6:
            color_field = "w3-flat-amethyst"
        elif pk % 10 == 7:
            color_field = "w3-metro-light-purple"
        elif pk % 10 == 8:
            color_field = "w3-flat-pumpkin"
        elif pk % 10 == 9:
            color_field = "w3-flat-orange"

        Reply.objects.create(to_reply=pk, message=form_data, left_margin=left_margin, color_style=color_field)
    return redirect('post-detail',pk=v)

def delete_func(pk):
    vist = Reply.objects.all().filter(to_reply=pk)
    for reply in vist:
        delete_func(reply.pk)
        reply.delete()

def delete_reply(request, pk, v):
    reply = Reply.objects.get(pk=pk)
    delete_func(reply.pk)
    reply.delete()
    return redirect('post-detail',pk=v)

blog_project/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

blog_project/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-colors-metro.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-colors-flat.css">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/cart.css' %}">

    <!-- my css -->
    <link rel="stylesheet" type="text/css" href="{% static 'blog/profileImage.css' %}">

    <script type="text/javascript">
      function getCookie(name) {
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }
      const csrftoken = getCookie('csrftoken');
    </script>
  


    {% if title %}
        <title>Django Blog - {{ title }}</title>
    {% else %}
        <title>Django Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">Campus</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'store' %}">Store</a>
              <a class="nav-item nav-link" style="min-width:20px" href="{% url 'learning' %}">Artificial Intelligence</a>

              {% if user.is_authenticated %}
                {% if user.is_superuser %}
                  <a class="nav-item nav-link" href="{% url 'store_new_item' %}">New Product</a>
                {% endif %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
              {% endif %}
              <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                <div class="form-inline my-2 my-lg-0" style="min-width:20px">
          	     	<a href="{% url 'cart' %}">
          	    		<img  id="cart-icon" src="{% static 'images/cart.png' %}">
          	    	</a>
          	    	<p id="cart-total">{{user.order_set.count}}</p>
	              </div>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div>
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{message.tags}}">
                {{message}}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>

</body>
</html>

blog_project/blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
<div class="row">
  <div class="col-md-8">
    {% for post in posts %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.profile_pic.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
  </div>

    <div class="col-md-4">
      <div class="content-section">
        <h3>Our Sidebar</h3>
        <p class='text-muted'>You can put any information here you'd like.
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Posts</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
          </ul>
        </p>
      </div>
      <a class="btn btn-success btn-bg" style="border-radius:5px;" href="{% url 'post-new' %}">Create New Post</a>
    </div>
</div>
{% endblock content %}

blog_project/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h3>Are you sure that you wanna delete your dark {{object}} post?</h3>
                {{ form }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog_project/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ object.author.profile.profile_pic.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'user-posts' object.author.username %}">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
      </div>
      <h2 class="article-title">{{ object.title }}</h2>
      <p class="article-content">{{ object.text }}</p>
    </div>
  </article>
        {% if object.author == user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.id %}">Delete</a>
          </div>
        {% endif %}
  {% for reply in reply_list %}
  <div class={{reply.color_style}} style="margin-left:{{reply.left_margin}}px; width:500px; margin-top:10px; box-sizing:border-box; border:1px solid #ccc; border-radius:4px;">
    <p style="color:white; display:inline;" class="w-70% ml-2">{{reply.message}}</p>
    <button class="kyy" data-id="{{reply.id}}" style="outline:none; background-color:inherit; border:0; cursor:pointer;">Reply</button>
    <a href="{% url 'delete-reply' pk=reply.id v=object.id %}">Delete</a>
    <div style="display: none;" id="{{reply.id}}">
      <form style="display:inline;" method="POST" action="{%url 'reply' pk=reply.id v=object.id%}">
        {% csrf_token %}
        <input style="border:0; border-radius:4px; margin-left:3px;" type="text" name="message" placeholder="Type your reply here.." required/>
        <input class="btn btn-success btn-sm" style="border-radius:4px; margin-bottom:6px;" type="submit" value="submit"/>
      </form>
      <button class="btn btn-primary btn-sm shyy" style="border-radius:4px; margin-bottom:6px;" type="submit" data-id="{{reply.id}}" value="submit">cancel</button>
    </div>
  </div>
  {% endfor %}

<script type="text/javascript">
  var list = document.getElementsByClassName("kyy")
  for(var i=0;i<list.length;i++){
    list[i].addEventListener('click',function(){
    var formid = this.dataset.id
    document.getElementById(formid).style.removeProperty( 'display' );
  })
  }
  var nist = document.getElementsByClassName("shyy")
  for(var i=0;i<nist.length;i++){
    nist[i].addEventListener('click',function(){
    var cancelid = this.dataset.id
    document.getElementById(cancelid).style.display = "none";
  })
  }
</script>

{% endblock content %}

blog_project/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Add Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

blog_project/blog/templates/blog/user_post.html
{% extends "blog/base.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ posts.first.author.post_set.count }})</h1>
    {% for post in posts %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.profile_pic.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock content %}